-- 02-service-seed.sql
--
-- 把还原到 public 的单体演示数据迁移进各业务 schema（镜像 scripts/migrate_monolith_data.py 的
-- public -> user_service/content_service/social_service 映射，但只覆盖备份中真实存在的表）。
-- 由 k8s Job data-seed 调用，位于 schema-migration（创建角色/schema/空表）之后、业务服务启动之前。
--
-- 幂等设计：仅当源(public.*)与目标(schema.*)表都存在时才写入；INSERT 全部 ON CONFLICT DO NOTHING，
-- 因此重复部署、Kind 集群复用时不会覆盖已有数据。
\set ON_ERROR_STOP on

SELECT
    CASE WHEN to_regclass('public.users')           IS NOT NULL
          AND to_regclass('user_service.users')     IS NOT NULL THEN 1 ELSE 0 END AS s_users,
    CASE WHEN to_regclass('public.categories')          IS NOT NULL
          AND to_regclass('content_service.categories') IS NOT NULL THEN 1 ELSE 0 END AS s_categories,
    CASE WHEN to_regclass('public.videos')           IS NOT NULL
          AND to_regclass('content_service.videos')  IS NOT NULL THEN 1 ELSE 0 END AS s_videos,
    CASE WHEN to_regclass('public.comments')          IS NOT NULL
          AND to_regclass('social_service.comments')  IS NOT NULL THEN 1 ELSE 0 END AS s_comments,
    CASE WHEN to_regclass('public.danmaku')           IS NOT NULL
          AND to_regclass('social_service.danmaku')   IS NOT NULL THEN 1 ELSE 0 END AS s_danmaku,
    CASE WHEN to_regclass('public.live_rooms')        IS NOT NULL
          AND to_regclass('social_service.live_rooms') IS NOT NULL THEN 1 ELSE 0 END AS s_live_rooms
\gset

\if :s_users
INSERT INTO user_service.users
    (id, account, password_hash, nickname, avatar, bio, user_type, status, created_at, updated_at)
SELECT id, account, password_hash, nickname, avatar, bio, user_type, status, created_at, updated_at
FROM public.users
ON CONFLICT DO NOTHING;

-- 备份不携带 stream_key（local gate 同样在迁移后补发），此处镜像该行为。
UPDATE user_service.users
   SET stream_key = substr(md5(id::text), 1, 20)
 WHERE stream_key IS NULL;
\endif

\if :s_categories
INSERT INTO content_service.categories (id, name, type, sort_order)
SELECT id, name, type, sort_order
FROM public.categories
ON CONFLICT DO NOTHING;

-- categories 是 GENERATED BY DEFAULT AS IDENTITY：补发序列，避免后续插入主键冲突。
SELECT setval(
    pg_get_serial_sequence('content_service.categories', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM content_service.categories), 1)
);
\endif

\if :s_videos
INSERT INTO content_service.videos
    (id, title, description, tags, cover_url, video_url, duration, category_id,
     view_count, like_count, comment_count, favorite_count, uploader_id,
     audit_status, status, created_at, updated_at)
SELECT id, title, description, tags, cover_url, video_url, duration, category_id,
       view_count, like_count, comment_count, favorite_count, uploader_id,
       audit_status, status, created_at, updated_at
FROM public.videos
ON CONFLICT DO NOTHING;
\endif

\if :s_comments
INSERT INTO social_service.comments
    (id, content, user_id, video_id, parent_id, reply_to_user_id, like_count, is_top, created_at)
SELECT id, content, user_id, video_id, parent_id, reply_to_user_id, like_count, is_top, created_at
FROM public.comments
ON CONFLICT DO NOTHING;
\endif

\if :s_danmaku
INSERT INTO social_service.danmaku
    (id, content, color, position, user_id, target_id, target_type, video_time, created_at)
SELECT id, content, color, position, user_id, target_id, target_type, video_time, created_at
FROM public.danmaku
ON CONFLICT DO NOTHING;
\endif

\if :s_live_rooms
INSERT INTO social_service.live_rooms
    (id, title, description, category_id, cover, stream_key, push_url, pull_url,
     anchor_id, online_count, start_time, end_time, status, created_at)
SELECT id, title, description, category_id, cover, stream_key, push_url, pull_url,
       anchor_id, online_count, start_time, end_time, status, created_at
FROM public.live_rooms
ON CONFLICT DO NOTHING;
\endif
