apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"user-service","namespace":"streamhub-ms"},"spec":{"behavior":{"scaleDown":{"policies":[{"periodSeconds":15,"type":"Percent","value":100}],"stabilizationWindowSeconds":30},"scaleUp":{"policies":[{"periodSeconds":15,"type":"Pods","value":2}],"stabilizationWindowSeconds":0}},"maxReplicas":4,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":40,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"user-service"}}}
  creationTimestamp: "2026-08-31T01:35:58Z"
  generation: 1
  name: user-service
  namespace: streamhub-ms
  resourceVersion: "12160"
  uid: 25db3597-e4f7-4ee1-ac53-3e7b60d870ed
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 30
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 4
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 40
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
status:
  conditions:
  - lastTransitionTime: "2026-08-31T01:36:10Z"
    message: the HPA controller was able to update the target scale to 1
    reason: SucceededRescale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-08-31T01:52:13Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-08-31T02:39:19Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  - lastTransitionTime: "2026-08-31T01:36:40Z"
    message: the HPA controller did not scale the workload to zero
    reason: NotScaledToZero
    status: "False"
    type: ScaledToZero
  currentMetrics:
  - resource:
      current:
        averageUtilization: 3
        averageValue: 3m
      name: cpu
    type: Resource
  currentReplicas: 4
  desiredReplicas: 1
  lastScaleTime: "2026-08-31T02:39:34Z"
  observedGeneration: 1
