\set ON_ERROR_STOP on

SET ROLE streamhub_user_service;
SET search_path TO user_service;

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    account VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    avatar TEXT DEFAULT '',
    bio TEXT DEFAULT '',
    user_type SMALLINT DEFAULT 0,
    status SMALLINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    stream_key VARCHAR(20) UNIQUE
);
CREATE INDEX IF NOT EXISTS ix_users_account ON users (account);

CREATE TABLE IF NOT EXISTS follows (
    id UUID PRIMARY KEY,
    follower_id UUID NOT NULL,
    followee_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_follow_pair UNIQUE (follower_id, followee_id)
);
CREATE INDEX IF NOT EXISTS ix_follows_follower ON follows (follower_id);
CREATE INDEX IF NOT EXISTS ix_follows_followee ON follows (followee_id);

CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY,
    user_a_id UUID NOT NULL,
    user_b_id UUID NOT NULL,
    last_message_id UUID,
    last_message_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_conversation_pair UNIQUE (user_a_id, user_b_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES conversations(id),
    sender_id UUID NOT NULL,
    receiver_id UUID NOT NULL,
    content TEXT NOT NULL,
    message_type SMALLINT DEFAULT 0,
    is_recalled BOOLEAN DEFAULT false,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    recalled_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_messages_conv_created
    ON messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS ix_messages_receiver_unread
    ON messages (receiver_id, is_read);

CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY,
    recipient_id UUID NOT NULL REFERENCES users(id),
    sender_id UUID REFERENCES users(id),
    notif_type SMALLINT DEFAULT 0,
    target_type SMALLINT DEFAULT 0,
    target_id UUID,
    content TEXT DEFAULT '',
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_notif_recipient_unread
    ON notifications (recipient_id, is_read, created_at);

CREATE TABLE IF NOT EXISTS processed_events (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

RESET ROLE;

SET ROLE streamhub_content_service;
SET search_path TO content_service;

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type SMALLINT DEFAULT 0,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS videos (
    id UUID PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description TEXT DEFAULT '',
    tags VARCHAR[] DEFAULT ARRAY[]::VARCHAR[],
    cover_url TEXT DEFAULT '',
    video_url TEXT DEFAULT '',
    duration INTEGER DEFAULT 0,
    category_id INTEGER REFERENCES categories(id),
    view_count INTEGER DEFAULT 0,
    like_count INTEGER DEFAULT 0,
    comment_count INTEGER DEFAULT 0,
    favorite_count INTEGER DEFAULT 0,
    uploader_id UUID,
    audit_status SMALLINT DEFAULT 0,
    status SMALLINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    reject_reason TEXT
);

CREATE TABLE IF NOT EXISTS integration_outbox (
    id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_content_outbox_pending
    ON integration_outbox (status, next_attempt_at);

CREATE TABLE IF NOT EXISTS processed_events (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

RESET ROLE;

SET ROLE streamhub_social_service;
SET search_path TO social_service;

CREATE TABLE IF NOT EXISTS comments (
    id UUID PRIMARY KEY,
    content TEXT NOT NULL,
    user_id UUID NOT NULL,
    video_id UUID NOT NULL,
    parent_id UUID,
    reply_to_user_id UUID,
    like_count INTEGER DEFAULT 0,
    is_top BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS comment_mentions (
    id UUID PRIMARY KEY,
    comment_id UUID NOT NULL REFERENCES comments(id),
    mentioned_user_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_comment_mention UNIQUE (comment_id, mentioned_user_id)
);
CREATE INDEX IF NOT EXISTS ix_mention_user ON comment_mentions (mentioned_user_id);

CREATE TABLE IF NOT EXISTS video_likes (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    video_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_user_video_like UNIQUE (user_id, video_id)
);
CREATE INDEX IF NOT EXISTS ix_video_likes_user ON video_likes (user_id);
CREATE INDEX IF NOT EXISTS ix_video_likes_video ON video_likes (video_id);

CREATE TABLE IF NOT EXISTS video_favorites (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    video_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_user_video_favorite UNIQUE (user_id, video_id)
);
CREATE INDEX IF NOT EXISTS ix_video_favorites_user ON video_favorites (user_id);
CREATE INDEX IF NOT EXISTS ix_video_favorites_video ON video_favorites (video_id);

CREATE TABLE IF NOT EXISTS video_interaction_baselines (
    video_id UUID PRIMARY KEY,
    like_count INTEGER NOT NULL DEFAULT 0 CHECK (like_count >= 0),
    comment_count INTEGER NOT NULL DEFAULT 0 CHECK (comment_count >= 0),
    favorite_count INTEGER NOT NULL DEFAULT 0 CHECK (favorite_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS danmaku (
    id UUID PRIMARY KEY,
    content TEXT NOT NULL,
    color VARCHAR(20) DEFAULT '#FFFFFF',
    position SMALLINT DEFAULT 0,
    user_id UUID NOT NULL,
    target_id UUID NOT NULL,
    target_type SMALLINT DEFAULT 0,
    video_time INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS live_rooms (
    id UUID PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description TEXT DEFAULT '',
    category_id INTEGER,
    cover TEXT DEFAULT '',
    stream_key VARCHAR(80) NOT NULL UNIQUE,
    push_url TEXT DEFAULT '',
    pull_url TEXT DEFAULT '',
    anchor_id UUID NOT NULL,
    online_count INTEGER DEFAULT 0,
    start_time TIMESTAMPTZ DEFAULT now(),
    end_time TIMESTAMPTZ,
    status SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reports (
    id UUID PRIMARY KEY,
    reporter_id UUID NOT NULL,
    target_type SMALLINT NOT NULL,
    target_id UUID NOT NULL,
    reason TEXT NOT NULL,
    status SMALLINT DEFAULT 0,
    handler_id UUID,
    handled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_reports_target ON reports (target_type, target_id);
CREATE INDEX IF NOT EXISTS ix_reports_status ON reports (status);

CREATE TABLE IF NOT EXISTS sensitive_words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS integration_outbox (
    id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_social_outbox_pending
    ON integration_outbox (status, next_attempt_at);

CREATE TABLE IF NOT EXISTS processed_events (
    event_id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

RESET ROLE;
