apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: streamhub-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
      containers:
        - name: content-service
          image: streamhub-content-service:replace-me
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: streamhub-ms-config
                  key: APP_VERSION
            - name: SERVICE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: streamhub-ms-config
                  key: APP_VERSION
            - name: CONTENT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: streamhub-ms-secrets
                  key: CONTENT_DATABASE_URL
            - name: USER_SERVICE_URL
              value: http://user-service:8000
            - name: SOCIAL_SERVICE_URL
              value: http://social-service:8000
            - name: SERVICE_CONNECT_TIMEOUT_SECONDS
              value: "0.5"
            - name: SERVICE_TOTAL_TIMEOUT_SECONDS
              value: "1.5"
            - name: MINIO_ENDPOINT
              value: minio-ms:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streamhub-ms-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: streamhub-ms-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_BUCKET
              value: streamhub-media
            - name: MINIO_SECURE
              value: "false"
            - name: OUTBOX_WORKER_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: streamhub-ms
spec:
  type: ClusterIP
  selector:
    app: content-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
